apiVersion: v1
kind: BuildConfig
metadata:
  name: nodejs-ex-pipeline
spec:
  source:
    git:
      uri: https://github.com/jonathanwhitby/nodejs-ex.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile:
  type: JenkinsPipeline
